.PHONY: clean All

All:
	@echo "----------Building project:[ Calculadora - Debug ]----------"
	@cd "Calculadora" && "$(MAKE)" -f  "Calculadora.mk"
clean:
	@echo "----------Cleaning project:[ Calculadora - Debug ]----------"
	@cd "Calculadora" && "$(MAKE)" -f  "Calculadora.mk" clean
